/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnidemo_JNITest */

#ifndef _Included_com_jnidemo_JNITest
#define _Included_com_jnidemo_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_JNITest
 * Method:    nativeGetStudentInfo
 * Signature: ()Lcom/jnidemo/Student;
 */
JNIEXPORT jobject JNICALL Java_com_jnidemo_JNITest_nativeGetStudentInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
